In [62]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [63]:
Listings_df = pd.read_csv(
    r"C:\Users\ADITYA\Downloads\Airbnb+Data\Airbnb Data\Listings.csv",
    engine="python",
    encoding="latin1",
    on_bad_lines="skip"
)

In [64]:
Listings_df

,Unnamed: 0,listing_id,host_id,host_since,host_response_rate,host_acceptance_rate,host_is_superhost,host_total_listings_count,host_has_profile_pic,host_identity_verified,...,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,instant_bookable,host_experience_years,host_experience_group
0,0,281420,1466919,2011-03-12,1.0,0.98,f,1.0,t,f,...,100.0,10.0,10.0,10.0,10.0,10.0,10.0,f,14.821918,10+ yrs
1,1,3705183,10328771,NaN,1.0,0.98,f,1.0,t,t,...,100.0,10.0,10.0,10.0,10.0,10.0,10.0,f,NaN,Unknown
2,2,4082273,19252768,NaN,1.0,0.98,f,1.0,t,f,...,100.0,10.0,10.0,10.0,10.0,10.0,10.0,f,NaN,Unknown
3,3,4797344,10668311,NaN,1.0,0.98,f,1.0,t,t,...,100.0,10.0,10.0,10.0,10.0,10.0,10.0,f,NaN,Unknown
4,4,4823489,24837558,NaN,1.0,0.98,f,1.0,t,f,...,100.0,10.0,10.0,10.0,10.0,10.0,10.0,f,NaN,Unknown
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
279707,279707,38338635,31161181,NaN,1.0,0.98,f,1.0,t,t,...,100.0,10.0,10.0,10.0,10.0,10.0,10.0,f,NaN,Unknown
279708,279708,38538692,10294858,NaN,1.0,0.98,f,1.0,t,t,...,100.0,10.0,10.0,10.0,10.0,10.0,10.0,f,NaN,Unknown
279709,279709,38683356,2238502,NaN,1.0,0.98,f,1.0,t,t,...,100.0,10.0,10.0,10.0,10.0,10.0,10.0,f,NaN,Unknown
279710,279710,39659000,38633695,NaN,1.0,0.98,f,1.0,t,t,...,100.0,10.0,10.0,10.0,10.0,10.0,10.0,f,NaN,Unknown
279711,279711,40219504,6955618,NaN,1.0,0.98,f,1.0,t,t,...,100.0,10.0,10.0,10.0,10.0,10.0,10.0,f,NaN,Unknown

In [65]:
Listings_df.head()

,Unnamed: 0,listing_id,host_id,host_since,host_response_rate,host_acceptance_rate,host_is_superhost,host_total_listings_count,host_has_profile_pic,host_identity_verified,...,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,instant_bookable,host_experience_years,host_experience_group
0,0,281420,1466919,2011-03-12,1.0,0.98,f,1.0,t,f,...,100.0,10.0,10.0,10.0,10.0,10.0,10.0,f,14.821918,10+ yrs
1,1,3705183,10328771,NaN,1.0,0.98,f,1.0,t,t,...,100.0,10.0,10.0,10.0,10.0,10.0,10.0,f,NaN,Unknown
2,2,4082273,19252768,NaN,1.0,0.98,f,1.0,t,f,...,100.0,10.0,10.0,10.0,10.0,10.0,10.0,f,NaN,Unknown
3,3,4797344,10668311,NaN,1.0,0.98,f,1.0,t,t,...,100.0,10.0,10.0,10.0,10.0,10.0,10.0,f,NaN,Unknown
4,4,4823489,24837558,NaN,1.0,0.98,f,1.0,t,f,...,100.0,10.0,10.0,10.0,10.0,10.0,10.0,f,NaN,Unknown

In [66]:
Listings_df.isnull().sum()

Unnamed: 0                          0
listing_id                          0
host_id                             0
host_since                     167039
host_response_rate                  0
host_acceptance_rate                0
host_is_superhost                   0
host_total_listings_count           0
host_has_profile_pic                0
host_identity_verified              0
neighbourhood                       0
city                                0
latitude                            0
longitude                           0
property_type                       0
room_type                           0
accommodates                        0
bedrooms                            0
amenities                           0
price                               0
minimum_nights                      0
maximum_nights                      0
review_scores_rating                0
review_scores_accuracy              0
review_scores_cleanliness           0
review_scores_checkin               0
review_scores_communication         0
review_scores_location              0
review_scores_value                 0
instant_bookable                    0
host_experience_years          167039
host_experience_group               0
dtype: int64

In [67]:
Listings_df.shape

(279712, 32)

In [68]:
Listings_df.duplicated().sum()

0

In [75]:
drop_Listings_df_cols = [ "district","name","host_location","host_response_time",
    "host_picture_url","host_experience_years","host_since"
]

Listings_df.drop(columns=drop_Listings_df_cols, inplace=True, errors="ignore")

In [76]:
Listings_df["price"].dtype

dtype('int64')

In [77]:
mean = Listings_df[
    [
        "review_scores_rating",
        "review_scores_accuracy",
        "review_scores_cleanliness",
        "review_scores_checkin",
        "review_scores_communication",
        "review_scores_location",
        "review_scores_value",
    ]
].mean()

In [78]:
mean

review_scores_rating           93.405195
review_scores_accuracy          9.565476
review_scores_cleanliness       9.312869
review_scores_checkin           9.701534
review_scores_communication     9.698593
review_scores_location          9.633994
review_scores_value             9.335364
dtype: float64

In [79]:
review_cols = [
    "review_scores_rating",
    "review_scores_accuracy",
    "review_scores_cleanliness",
    "review_scores_checkin",
    "review_scores_communication",
    "review_scores_location",
    "review_scores_value",
]

mean = Listings_df[review_cols].mean()

Listings_df[review_cols] = Listings_df[review_cols].fillna(mean)

In [89]:
for col in ["host_response_rate", "host_acceptance_rate"]:
    Listings_df[col] = (
        Listings_df[col]
        .astype(str)
        .str.replace("%","", regex=False)
        .replace("nan", None)
        .astype(float)
    )
    Listings_df[col].fillna(Listings_df[col].median(), inplace=True)

In [90]:
Listings_df["host_is_superhost"].fillna("f", inplace=True)

In [91]:
Listings_df["host_total_listings_count"].fillna(
    Listings_df["host_total_listings_count"].median(),
    inplace=True
)

In [92]:
for col in ["host_has_profile_pic", "host_identity_verified"]:
    Listings_df[col].fillna("f", inplace=True)

In [93]:
Listings_df["bedrooms"].fillna(Listings_df["bedrooms"].median(), inplace=True)

In [98]:
Listings_df.to_csv(r"C:\Users\ADITYA\Downloads\Airbnb+Data\Airbnb Data\Listings.csv", index = " False", header = "None")